INFERANALYZE = '/usr/local/Cellar/infer/0.13.0/lib/infer/infer/bin/infer-analyze' --no-report --results-dir '/Users/shivaiah.mahesha/Desktop/Projects/SDK/ReviewKit/ios-perftracking/fastlane/infer-out' --compilation-database-escaped '/var/folders/ln/16w_m84d48s4f41fmp8cp4krfm4vj_/T/cdb60b930.json'

CLUSTERS=

default: test

all: test

test: $(CLUSTERS)
	@echo


clean:
	rm -f $(CLUSTERS)
