opt_out_usage
default_platform :ios

platform :ios do
  before_all do
    xcversion(
      version: ">= 8.0"
    )
  end

  desc 'Run Static Code Analzer'
  lane :analyzer do |options|
    # Installing infer
    sh "brew install infer"
    #sh "infer run -- xcodebuild ../RPerformanceTracking.xcworkspace -scheme RPerformanceTracking"
    #sh "infer run -- xcodebuild -workspace ../RPerformanceTracking.xcworkspace -scheme HostApp"
    sh "infer run --keep-going -- xcodebuild -workspace ../RPerformanceTracking.xcworkspace -scheme RPerformanceTracking -sdk iphonesimulator -configuration Release clean build"
  end
  

  desc 'Run all the tests'
  lane :tests do |options|
    cocoapods
    scan(
      clean: true,
      skip_build: true,
      output_directory: './artifacts/unit-tests',
      scheme: 'Tests',
      device: 'iPhone 8',
      code_coverage: true
    )

    slather(
      output_directory: './artifacts/coverage',
      scheme: 'Tests',
      cobertura_xml: true,
      proj: './RPerformanceTracking.xcodeproj',
      workspace: './RPerformanceTracking.xcworkspace',
      binary_basename: 'RPerformanceTracking',
      ignore: [
        '../*',
      ]
    )
  end

  desc 'CI build'
  lane :ci do |options|
    # Use env variables to set up config & location endpoints/keys in order
    # to keep those items secret
    set_info_plist_value(path: "./Tests/HostApp/Info.plist",
                         key: "RPTConfigAPIEndpoint",
                         value: ENV['REM_FL_RPT_CONFIG_ENDPOINT'] || "https://performance-endpoint.com")
    set_info_plist_value(path: "./Tests/HostApp/Info.plist",
                         key: "RPTLocationAPIEndpoint",
                         value: ENV['REM_FL_RPT_LOCATION_ENDPOINT'] || "https://location-endpoint.com")
    set_info_plist_value(path: "./Tests/HostApp/Info.plist",
                         key: "RPTSubscriptionKey",
                         value: ENV['REM_FL_RPT_SUBSCRIPTION_KEY'] || "SUBSCRIPTION_KEY")
    tests(options)
  end

  desc 'Module Pre-Release checks'
  lane :release do |options|

    release_tag = options[:tag]
    module_name = options[:module]
    release_branch = options[:branch]


    # Remove the newline character from the release_tag otherwise it won't enter into if statement
    release_tag = release_tag.to_s.strip

    unless release_tag.empty?
      if !git_tag_exists(tag: "#{release_tag}")
        puts "#{release_tag} version doesn't exist, it will be tagged to master branch and push it to the remote. After the version is tagged, run 'release' lane again"

      ensure_git_branch(
          branch: "#{release_branch}"
      )

      add_git_tag(
         tag: "#{release_tag}"
      )
      sh "git push origin #{release_tag}"

      end
    end

    lint(options)

    puts "generate documentation for #{module_name} version #{release_tag}"
    documentation(
      module_name: module_name,
      module_version: release_tag
    )
  end

  desc 'Lint the podspec'
  lane :lint do |options|
    pod_lib_lint(sources: [options[:spec_source], "https://github.com/CocoaPods/Specs"], allow_warnings: true, verbose: false)
  end

end
# vim:syntax=ruby:et:sts=2:sw=2:ts=2:ff=unix:
