# Import base_config from git
import_from_git(url: 'https://github.com/rakutentech/ios-buildconfig.git')

platform :ios do
  desc "Build everything"
  lane :ci do |options|
    # Use env variables to set up config & location endpoints/keys in order
    # to keep those items secret
    set_info_plist_value(path: "./Tests/HostApp/Info.plist",
                         key: "RPTConfigAPIEndpoint",
                         value: ENV['REM_FL_RPT_CONFIG_ENDPOINT'] || "https://performance-endpoint.com")
    set_info_plist_value(path: "./Tests/HostApp/Info.plist",
                         key: "RPTLocationAPIEndpoint",
                         value: ENV['REM_FL_RPT_LOCATION_ENDPOINT'] || "https://location-endpoint.com")
    set_info_plist_value(path: "./Tests/HostApp/Info.plist",
                         key: "RPTSubscriptionKey",
                         value: ENV['REM_FL_RPT_SUBSCRIPTION_KEY'] || "SUBSCRIPTION_KEY")
    shared_tests(options)
  end
end
# vim:syntax=ruby:et:sts=2:sw=2:ts=2:ff=unix:
